- bin/kintsugi
- kintsugi.gemspec
- lib/kintsugi/version.rb
Helps looks nice:
```
> bin/kintsugi --help
Kintsugi, version 1.0.0
Copyright (c) 2021 Lightricks
Usage: kintsugi [pbxproj_filepath] [options]
--changes-output-path=PATH   Path to which changes applied to the project are written in JSON format. Used for debug purposes.
-h, --help                       Prints this help
-v, --version                    Show version
```
Because argument count check is done without the parser, argument count errors look a tad strange:
```
> bin/kintsugi
Incorrect number of arguments
Kintsugi, version 1.0.0
Copyright (c) 2021 Lightricks
Usage: kintsugi [pbxproj_filepath] [options]
--changes-output-path=PATH   Path to which changes applied to the project are written in JSON format. Used for debug purposes.
-h, --help                       Prints this help
-v, …
```
> bin/kintsugi: Add version and copyright information.

- lib/kintsugi/apply_change_to_project.rb
- spec/kintsugi_apply_change_to_project_spec.rb
If the applied change removed a value and the existing value is
different from the removed value, it is considered a conflict.
However, this is not true in the case the existing value was already
removed.
In addition, improve messages in case of real conflicts when dealing
with removal of simple attributes.
> apply_change_to_project: Fix removal of simple value that's nil already.

- lib/kintsugi.rb
Resetting the state of files is outside the scope, as Kintsugi should
only concern itself with creating a file with the resolved conflicts.
> kintsugi.rb: Don't reset Git file state after resolving conflicts.

- kintsugi.gemspec
Kintsugi works well with Xcodeproj 1.21.0, so the required version is
set to be between 1.19.0 and 1.21.0.
> kintsugi: Relax required versions for Xcodeproj dependency.

- README.md
Hello :)
This little change to the Readme adds two alternatives besides XcodeGen: Xcake (currently maintained by @igor-makarov) and Tuist (disclaimer: I'm a contributor).
> Add Xcake and Tuist as alternatives

- bin/kintsugi
- lib/kintsugi.rb
- lib/kintsugi/apply_change_to_project.rb
- lib/kintsugi/error.rb
Instead of printing the stack trace, just print the errors.
> kintsugi: Handle expected errors gracefully.

- lib/kintsugi/cli.rb
If the containing directory of the attributes file didn't exist,
appending the line to the git attributes file would fail.
> install-driver: Create attributes directory before appending line.

- lib/kintsugi.rb
The path to the project is quoted so Kintsugi will work even if the path
contains spaces.
> kintsugi: Fix for project paths with spaces.

- lib/kintsugi/cli.rb
Also have at least 3 spaces between the subcommand and the description,
same as the case with the parameters.
> cli: Align subcommands descriptions vertically.

- lib/kintsugi.rb
If the project had spaces in name, the single path argument was
considered as multiple arguments in bash because it wasn't wrapped with
quotes.
> kintsugi: Fix crash for project with spaces in name.

- spec/spec_helper.rb
One feature enables marking focused tests with "fit", while the other
runs all the tests if there are no focused tests.
> spec_helper: Support "fit" focused tests.

- spec/kintsugi_apply_change_to_project_spec.rb
If the diff doesn't contain any changes it means that the test that
uses it tries to apply an empty diff to a project. This means that in
practice the test doesn't check anything.
> apply_change_to_project_spec: Raise if diff contains no changes.

- bin/kintsugi
Previously when ArgumentError or MergeError occurred the exit code of
the program was 0 because `exit` wasn't invoked explicitly.
> kintsugi: Fix error codes on exceptions.

- lib/kintsugi/cli.rb
When `install-driver` ran, The git attributes file path was
retrieved by running `git config --global core.attributesfile`,
Since this command ends with `\n`, in cases where it was configured
the file path got `\n` added to it.
Chomping the configured git attributes file path resolved this issue.
> cli: fix incorrect git attributes file name.

- lib/kintsugi/apply_change_to_project.rb
- spec/kintsugi_apply_change_to_project_spec.rb
When adding a component with simple attributes, these attributes might
have default values that aren't `nil`. Previously, when such a thing
occurred it would result in a `MergeError`, because the removed change
was assumed to be `nil` since the component was just added, but in
practice it would be set to the default value.
The solution is to set the removed change value to the default value.
> apply change: Fix adding component with non default simple attributes.

- bin/kintsugi
- kintsugi.gemspec
- lib/kintsugi.rb
- lib/kintsugi/merge.rb
- spec/kintsugi_integration_spec.rb
- kintsugi.gemspec: Add git as development dependency.
- Add integration tests.
> Kintsugi: Add integration tests.

- lib/kintsugi/merge.rb
> merge.rb: Refactor.

- lib/kintsugi/apply_change_to_project.rb
- spec/kintsugi_apply_change_to_project_spec.rb
Previously, moved files were removed from one group and added to
another. This caused the build files referencing them to remain
dangling. This was solved by identifying files that were moved and using
the appropriate functions to move them.
> Support merging conflicts with moved files.

- lib/kintsugi/apply_change_to_project.rb
- lib/kintsugi/cli.rb
- lib/kintsugi/settings.rb
- spec/kintsugi_apply_change_to_project_spec.rb
- Kintusgi: Add Settings class.
- Kintsugi: Avoid adding duplicates if settings don't allow.
> Kintsugi: Avoid adding duplicates if settings don't allow.

- lib/kintsugi/apply_change_to_project.rb
- spec/kintsugi_apply_change_to_project_spec.rb
There can be more than one reference proxy with the same display name in
the same project. Therefore the correct one needs to be searched
according to its remote ref.
In addition, since all the removed changes are treated as array in
`apply_change_to_project`, it can call the inner function
`child_component_of_object_list`.
> apply_change_to_project: Identify child reference proxy by remote ref.

- lib/kintsugi/apply_change_to_project.rb
- spec/kintsugi_apply_change_to_project_spec.rb
Also, refactor applying added changes for symmetry with removed changes.
> apply_change_to_project: Handle remove configuration list change.

- lib/kintsugi/apply_change_to_project.rb
- spec/kintsugi_apply_change_to_project_spec.rb
Previously, file references were treated as identical only if all the
change that describes them were identical. This was problematic in case
someone moved a file and change one of its attributes that wasn't part
of its identity, like the file encoding. In such a case the file would
not be identified as moved. Now however, it is identified by its path,
name and source tree.
> Kintsugi: Treat files as identical by a subset of their attributes.

- lib/kintsugi/apply_change_to_project.rb
- spec/kintsugi_apply_change_to_project_spec.rb
Until now it was assumed that `change` variable was always non nil and
containing the `rootObject` key. If that's not the case simply apply no
changes.
> apply_change_to_project: Ignore when diff is nil or without root object.

- lib/kintsugi/apply_change_to_project.rb
- spec/kintsugi_apply_change_to_project_spec.rb
The code assumed that a `file_ref` of a build file always existed and
it accessed its `path` property which would cause a crash.
> Kintsugi: Fix crash when a build file without file reference exists.

- lib/kintsugi/apply_change_to_project.rb
- spec/kintsugi_apply_change_to_project_spec.rb
Previously the code would crash because the containing group was `nil`.
Still the code raises a `MergeError` as it isn't clear whether the group
should be created again or the file/group addition should be ignored.
The same is done when trying to move a file or a group to a group that
doesn't exist.
> apply_change_to_project: Fix adding file or group to non existent group.

- lib/kintsugi/apply_change_to_project.rb
- spec/kintsugi_apply_change_to_project_spec.rb
The bug was reported here: https://github.com/Lightricks/Kintsugi/issues/104
Basically, when a file with a name that already exists is added to a
target, the search for the file only took into account the filename.
Instead, the file is searched for in `change_source_project` and its
group path is taken from there.
As a sidenote - Adding the UUID would also help, but would create other
sorts of problems because UUIDs are not always consistent between
project saves.
> apply_change_to_project: Fix adding file to target with existing name.

- lib/kintsugi/xcodeproj_extensions.rb
The crash happens when `target_proxy` is `nil`.
> xcodeproj_extensions: Fix crash in `PBXTargetDependency`.

- kintsugi.gemspec
CocoaPods 1.13.0 includes `Xcode 15 fix` that is required for Xcode 15 to avoid build errors.
https://github.com/CocoaPods/CocoaPods/releases/tag/1.13.0
It depends on xcodeproj 1.23.0.
> kintsugi.gemspec: bump xcodeproj for Xcode 15

- .github/workflows/tests.yml
Currently, the tests were running on ruby 2.6 and using latest
RubyGems. This is broken since latest RubyGems support Ruby>3. This is
fine since ruby 2.7 is now deprecated.
Kintsugi runs usually on macOS which comes built-in with ruby 2.6, so
it's worth keep testing on that version. So this commit add tests on
multiple ruby versions.
> CI: test on multiple ruby versions.

- lib/kintsugi/xcodeproj_extensions.rb
We have a build plugin which is a Swift package, it's represented as a
`XCSwiftPackageProductDependency` object. The display name contains a "plugin:"
prefix so when it's serialized it's everywhere. The problem is that Xcode
removes this prefix and uses the package name in the keys of the serialized
objects and in refs to them (in the comments).
Below is an example before and after the change.
before (wrong):
```
/* Begin XCSwiftPackageProductDependency section */
19AA76E52A9F557900F1F6A1 /* plugin:SomePackageName */ = {
isa = XCSwiftPackageProductDependency;
productName = "plugin:SomePackageName";
};
```
after (correct):
```
/* Begin XCSwiftPackageProductDependency section */
19AA76E52A9F557900F1F6A1 /* SomePackageName */ = {
isa = XCSwiftPackageProductDependency;
productName = …
```
> xcodeproj_extensions: fix wrong serialization with swift package target.

- .github/workflows/release.yml
Previously, ruby 2.6 with latest rubygems was used to publish them gem.
Latest rubygems doesn't support ruby 2.6 anymore and all is needed to
upload is latest rubygems, so this is used.
> Release: use head ruby version.

- kintsugi.gemspec
The xcodeproj gem 1.24.0 includes a fix issues including one fixing SPM package annotation and causing unwanted after a conflict resolution
> kintsugi.gemspec: bump xcodeproj

- spec/kintsugi_apply_change_to_project_spec.rb
This prevents the mistake where a test doesn't do anything because we
forgot to call the save function.
> spec: move project saving to within the copy function.

- lib/kintsugi/xcodeproj_extensions.rb
In case of a local Swift package, xcodeproj wrongfully uses the
`File.basename` of the path and Xcode fixes that to be the full path.
This commit patches the xcodeproj implementation and fixes it.
Below is an example before and after the change.
before (wrong):
```
/* Begin XCLocalSwiftPackageReference section */
BA78EB3B2C889B20000D85B2 /* XCLocalSwiftPackageReference "Package" */ = {
isa = XCLocalSwiftPackageReference;
relativePath = ../Path/To/Package;
};
```
after (correct)
```
/* Begin XCLocalSwiftPackageReference section */
BA78EB3B2C889B20000D85B2 /* XCLocalSwiftPackageReference "../Path/To/Package" */ = {
isa = XCLocalSwiftPackageReference;
relativePath = ../Path/To/Package;
};
```
> xcodeproj_extensions: fix wrong serialization with local swift packages.

- kintsugi.gemspec
Bump Xcodeproj version requirements to allow version `1.25.0`
[Older versions contain a dependency with a known security vulnerability, which is flagged by GitHub.](https://www.ruby-lang.org/en/news/2024/08/22/dos-rexml-cve-2024-43398/)
> Bump Xcodeproj to 1.25.0

- kintsugi.gemspec
Bump Xcodeproj version requirements to allow version 1.27.0
The latest version of cocoapods, `1.16.2` now requires at minimum 1.27.0 of `xcodeproj`
See these [release notes](https://github.com/CocoaPods/CocoaPods/releases)
This PR bumps Xcodeproj to restore compatibility between the latest versions of Kintsugi and Cocoapods.
I've verified that running `bundle install` within my project whose Gemfile depends on `kintsugi` now works. However I haven't tested the functionality of `kintsugi` for compatibility with `xcodeproj` 1.27.0 as I'm not sure what to test for.
I hope this is helpful, in any case.
Before this PR, running `bundle install` within my project root results in this error
```
Fetching https://github.com/pbsupplyco/Kintsugi.git
Fetching gem metadata from …
```
> Bump Xcodeproj to 1.27.0

- kintsugi.gemspec
Updated minimum xcodeproj dependency to 1.26.0 to ensure PBXFileSystemSynchronizedRootGroup support for Xcode 16 buildable folders.
> kintsugi.gemspec: require xcodeproj >= 1.26.0
